---
title: "FIGURE_1_QUALITY_TRIMMING"
format: html
editor_options: 
  chunk_output_type: console
---

# Import

```{r}
df_quality <- read.delim("quality_summary.tsv")
df_quality -> df_quality_ok
library(readxl)
df_clinic <- read_excel("df_clinic_final.xlsx")
df_clinic <- as.data.frame(df_clinic)
```

```{r}
df_quality <- df_quality[df_quality$Sample %in% df_clinic$Sample, ]
```

```{r}
df_quality_all <- merge(x = df_quality,
                        y = df_clinic[ , c("Sample", "Termness")],
                        all.x = TRUE,
                        by = "Sample")
```

```{r}
df_quality_all$Termness <- factor(df_quality_all$Termness,
                                  levels = c("term",
                                             "preterm"))
```


# Plot

```{r}
library(ggplot2)
library(ggsignif)

ggplot(data = df_quality_all,
       mapping = aes(x = Termness,
                     y = total_final,
                     fill = Termness)) +
  
  geom_boxplot(outliers = F) +

  geom_jitter(width = 0.1,
              alpha = 0.5) +
  
  scale_y_continuous(limits = c(0e7,8e7)) +
  
  scale_fill_manual(values = c("#FFD700", "#E08AF9")) +
  
   ggsignif:::geom_signif(comparisons =  list(c("term", "preterm")),
                         map_signif_level = function(p_ok) {

                          capture.output(cat(p_ok)) -> p_ok_final
                         paste0("p", " = ", p_ok_final)

                         },
                         textsize = 6,
                         vjust = -0.5,
                         # step_increase = 0.6,
                         test = "t.test",
                         test.args = list(paired = F)
                         ) +
  
  theme_classic(base_size = 19) +
  
  theme(legend.position = "none")

# ggsave(filename = "FIGURE_1_QUALITY_TRIMMING.svg",
#        width = 9,
#        height = 6)
```

# TOTAL FINAL

```{r}
df_quality_adult <- df_quality_ok[82:93 , ]

df_quality_adult$Termness <- "adult"

df_quality_final <- rbind(df_quality_all, 
                          df_quality_adult)
```


```{r}
ggplot(data = df_quality_final ,
       mapping = aes(x = Termness,
                     y = total_final,
                     fill = Termness)) +
  
  geom_boxplot(outliers = F) +

  geom_jitter(width = 0.1,
              alpha = 0.5) +
  
  scale_y_continuous(limits = c(0e7,12e7)) +
  
  scale_fill_manual(values = c("#E69F00", "#E08AF9", "lightgreen")) +
  
   ggsignif:::geom_signif(comparisons =  list(c("term", "preterm"),
                                              c("term", "adult"),
                                              c("preterm", "adult")),
                         map_signif_level = function(p_ok) {

                          capture.output(cat(p_ok)) -> p_ok_final
                         paste0("p", " = ", p_ok_final)

                         },
                         textsize = 6,
                         vjust = -0.2,
                         step_increase = 0.3,
                         test = "t.test",
                         test.args = list(paired = F)
                         ) +
  
  theme_classic(base_size = 19) +
  
  theme(legend.position = "none")

ggsave(filename = "FIGURE_1_QUALITY_TRIMMING_ADULT.svg",
       width = 9,
       height = 6)
```



so sanh giua 2 nhom:
1/ two sample t-test: voi gia dinh la du lieu cua 2 nhom normality va phuong sai bang nhau
(neu n > 30)

2/ man-whitney u-test (wilcoxon): voi gia dinh la du lieu cua 2 nhom ko can normality 











