---
title: "FIGURE_4B_BETA_DIVERSITY"
date: last-modified
format:
  html:
    toc: true
    toc-title: "TOC"
    toc-expand: 8
    toc-depth: 6
    toc-location: left
    code-fold: true
    code-summary: "Show the code"
    number-sections: false
    number-depth: 8
    page-layout: full
    embed-resources: true
    anchor-sections: true
    smooth-scroll: true
engine: knitr
knitr:
  opts_chunk:
    R.options:
      width: 120
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, results='hide'}
knitr::opts_chunk$set(message = FALSE,  
                      warning = FALSE)   
```

# DISTANCE

```{r}
library(readxl)
df_clinic <- read_excel("df_clinic_final.xlsx")
row.names(df_clinic) <- df_clinic$Sample
meta <- df_clinic

df_species <- read.delim("baby_species.tsv")
names(df_species)[1] <- "Sample"

df_species <- df_species[df_species$Sample %in% df_clinic$Sample, ]

df_species -> species
```


```{r}
library("ape")
library("vegan")
library("dplyr")
library("hagis")
library("ggplot2")

row.names(species) <- species[ , 1]

species <- species[row.names(df_clinic), ]

species <- species[ , -1]

row.names(species)

bray_distance <- vegan::vegdist(species,
                                method = "bray")

bray_distance_matrix <- as.matrix(bray_distance)
```

# PCOA

```{r}
princoor.pathotype <- pcoa(bray_distance_matrix) 

# barplot(princoor.pathotype$values$Relative_eig[1:10])

Axis1.percent <-
  princoor.pathotype$values$Relative_eig[[1]] * 100

Axis1.percent

Axis2.percent <-
  princoor.pathotype$values$Relative_eig[[2]] * 100

Axis2.percent


princoor.pathotype.data <-
  data.frame(
    Sample = rownames(princoor.pathotype$vectors),
    X = princoor.pathotype$vectors[, 1],
    Y = princoor.pathotype$vectors[, 2]
  )

row.names(princoor.pathotype.data) <- NULL

princoor.pathotype.data

# plot(princoor.pathotype.data[ , -1])
```

```{r}
library(dplyr)

princoor.pathotype.data |> dplyr:::arrange(Sample) -> princoor.pathotype.data

meta |> dplyr:::arrange(Sample) -> meta

identical(princoor.pathotype.data$Sample, meta$Sample)

princoor.pathotype.data$Termness <- meta$Termness

princoor.pathotype.data$Feeding_method <- meta$Feeding_method

princoor.pathotype.data$Delivery_mode <- meta$Delivery_mode

princoor.pathotype.data$Probiotics <- meta$Probiotics

princoor.pathotype.data$Antibiotics <- meta$Antibiotics

princoor.pathotype.data$Sex <- meta$Sex

princoor.pathotype.data$Ethnicity <- meta$Ethnicity
```

```{r}
make_centroids <- function(df) {
  transform(
    df,
    xend = mean(x, na.rm = TRUE),
    yend = mean(y, na.rm = TRUE)
  )
}

make_hull <- function(df) {
  df <- df[complete.cases(df), , drop = FALSE]
  hull <- chull(df$x, df$y)
  df[hull, , drop = FALSE]
}
```

# ADONIS

```{r}
# TERMNESS

row.names(bray_distance_matrix) -> sample_check

meta$Sample -> sample_ok
 
names(sample_ok) <- meta$Termness

sample_ok[order(match(sample_ok,sample_check))] -> group_factor

names(group_factor) -> group_factor_ok

group_factor -> group_factor_yes

names(group_factor_yes) <- NULL

identical(group_factor_yes, sample_check)

group_factor_ok <- factor(group_factor_ok)

group_factor_ok -> group_factor_Termness

####################################


# Sex

row.names(bray_distance_matrix) -> sample_check

meta$Sample -> sample_ok

names(sample_ok) <- meta$Sex

sample_ok[order(match(sample_ok,sample_check))] -> group_factor

names(group_factor) -> group_factor_ok

group_factor -> group_factor_yes

names(group_factor_yes) <- NULL

identical(group_factor_yes, sample_check)

group_factor_ok <- factor(group_factor_ok)

group_factor_ok -> group_factor_Sex


####################################


# Delivery_mode

row.names(bray_distance_matrix) -> sample_check

meta$Sample -> sample_ok

names(sample_ok) <- meta$Delivery_mode

sample_ok[order(match(sample_ok,sample_check))] -> group_factor

names(group_factor) -> group_factor_ok

group_factor -> group_factor_yes

names(group_factor_yes) <- NULL

identical(group_factor_yes, sample_check)

group_factor_ok <- factor(group_factor_ok)

group_factor_ok -> group_factor_Delivery_mode

####################################


# Feeding_group

row.names(bray_distance_matrix) -> sample_check

meta$Sample -> sample_ok

names(sample_ok) <- meta$Feeding_method

sample_ok[order(match(sample_ok,sample_check))] -> group_factor

names(group_factor) -> group_factor_ok

group_factor -> group_factor_yes

names(group_factor_yes) <- NULL

identical(group_factor_yes, sample_check)

group_factor_ok <- factor(group_factor_ok)

group_factor_ok -> group_factor_Feeding_method


###############

# Ethnicity

row.names(bray_distance_matrix) -> sample_check

meta$Sample -> sample_ok

names(sample_ok) <- meta$Ethnicity

sample_ok[order(match(sample_ok,sample_check))] -> group_factor

names(group_factor) -> group_factor_ok

group_factor -> group_factor_yes

names(group_factor_yes) <- NULL

identical(group_factor_yes, sample_check)

group_factor_ok <- factor(group_factor_ok)

group_factor_ok -> group_factor_Ethnicity

###############

# Probiotics

row.names(bray_distance_matrix) -> sample_check

meta$Sample -> sample_ok

names(sample_ok) <- meta$Probiotics

sample_ok[order(match(sample_ok,sample_check))] -> group_factor

names(group_factor) -> group_factor_ok

group_factor -> group_factor_yes

names(group_factor_yes) <- NULL

identical(group_factor_yes, sample_check)

group_factor_ok <- factor(group_factor_ok)

group_factor_ok -> group_factor_Probiotics

###############

# Antibiotics

row.names(bray_distance_matrix) -> sample_check

meta$Sample -> sample_ok

names(sample_ok) <- meta$Antibiotics

sample_ok[order(match(sample_ok,sample_check))] -> group_factor

names(group_factor) -> group_factor_ok

group_factor -> group_factor_yes

names(group_factor_yes) <- NULL

identical(group_factor_yes, sample_check)

group_factor_ok <- factor(group_factor_ok)

group_factor_ok -> group_factor_Antibiotics
```


```{r}
# per-manova
# permuatation
# m-anova, m multiple anova

set.seed(2026)
pathotype.adonis <- adonis2(bray_distance ~ group_factor_Termness + 
                              group_factor_Sex + 
                              group_factor_Delivery_mode +
                              group_factor_Feeding_method + 
                              group_factor_Ethnicity +
                              group_factor_Probiotics + 
                              group_factor_Antibiotics, 
                            by = "terms")

pathotype.adonis

```


```{r}
df_ok <- as.data.frame(pathotype.adonis)

row.names(df_ok) <- c("Termness",
                      "Sex",
                      "Delivery_mode",
                      "Feeding_method",
                      "Ethnicity",
                      "Probiotics",
                      "Antibiotics",
                      "Residual",
                      "Total")

df_ok
```




# PCOA | Termness

```{r}
princoor.pathotype.data$Termness <- factor(princoor.pathotype.data$Termness,
                                           levels = c("term",
                                                      "preterm"))
```


```{r, fig.width=9, fig.height=6}
yes <- paste0("R² = ", round(df_ok[row.names(df_ok) == "Termness" , "R2"], 4),
              " | F = ", round(df_ok[row.names(df_ok) == "Termness" , "F"], 4),
              " | p-value = ", round(df_ok[row.names(df_ok) == "Termness" , "Pr(>F)"], 4))


ggplot( princoor.pathotype.data, 
       aes(X,
           Y, 
           colour = Termness  )) + 
  geom_point(na.rm = TRUE) + 
  
  # As a stat, provide a geom
  stat_manual(
    geom = "segment", # function creates new xend/yend for segment
    fun = make_centroids,
    linewidth = 0.2,
    na.rm = TRUE
  ) +
  
  scale_color_manual(values = c("#FFD700", "purple")) +
  
  theme_bw(base_size = 16) +

  xlab(paste0("PCoA1 (", round(Axis1.percent, 2), "%)")) +
  ylab(paste0("PCoA2 (", round(Axis2.percent, 2), "%)")) +
  
  labs(title = "Bray-Curtis | Termness",
       subtitle = yes) +
  
  theme(panel.grid = element_blank())
```

# PCOA | Sex


```{r, fig.width=9, fig.height=6}
yes <- paste0("R² = ", round(df_ok[row.names(df_ok) == "Sex" , "R2"], 4),
              " | F = ", round(df_ok[row.names(df_ok) == "Sex" , "F"], 4),
              " | p-value = ", round(df_ok[row.names(df_ok) == "Sex" , "Pr(>F)"], 4))


ggplot( princoor.pathotype.data, 
       aes(X,
           Y, 
           colour = Sex  )) + 
  geom_point(na.rm = TRUE) + 
  
  # As a stat, provide a geom
  stat_manual(
    geom = "segment", # function creates new xend/yend for segment
    fun = make_centroids,
    linewidth = 0.2,
    na.rm = TRUE
  ) +
  
 scale_color_manual(values = c("#FFD700", "purple")) +
  
  theme_bw(base_size = 16) +

  xlab(paste0("PCoA1 (", round(Axis1.percent, 2), "%)")) +
  ylab(paste0("PCoA2 (", round(Axis2.percent, 2), "%)")) +
  
  labs(title = "Bray-Curtis | Sex",
       subtitle = yes) +
  
  theme(panel.grid = element_blank())
```

# PCOA | Delivery_mode


```{r, fig.width=9, fig.height=6}
yes <- paste0("R² = ", round(df_ok[row.names(df_ok) == "Delivery_mode" , "R2"], 4),
              " | F = ", round(df_ok[row.names(df_ok) == "Delivery_mode" , "F"], 4),
              " | p-value = ", round(df_ok[row.names(df_ok) == "Delivery_mode" , "Pr(>F)"], 4))


ggplot( princoor.pathotype.data, 
       aes(X,
           Y, 
           colour = Delivery_mode  )) + 
  geom_point(na.rm = TRUE) + 
  
  # As a stat, provide a geom
  stat_manual(
    geom = "segment", # function creates new xend/yend for segment
    fun = make_centroids,
    linewidth = 0.2,
    na.rm = TRUE
  ) +
  
   scale_color_manual(values = c("#FFD700", "purple")) +
  
  theme_bw(base_size = 16) +

  xlab(paste0("PCoA1 (", round(Axis1.percent, 2), "%)")) +
  ylab(paste0("PCoA2 (", round(Axis2.percent, 2), "%)")) +
  
  labs(title = "Bray-Curtis | Delivery mode",
       subtitle = yes) +
  
  theme(panel.grid = element_blank())
```


# PCOA | Feeding_method


```{r, fig.width=9, fig.height=6}
yes <- paste0("R² = ", round(df_ok[row.names(df_ok) == "Feeding_method" , "R2"], 4),
              " | F = ", round(df_ok[row.names(df_ok) == "Feeding_method" , "F"], 4),
              " | p-value = ", round(df_ok[row.names(df_ok) == "Feeding_method" , "Pr(>F)"], 4))


ggplot( princoor.pathotype.data, 
       aes(X,
           Y, 
           colour = Feeding_method  )) + 
  geom_point(na.rm = TRUE) + 
  
  # As a stat, provide a geom
  stat_manual(
    geom = "segment", # function creates new xend/yend for segment
    fun = make_centroids,
    linewidth = 0.2,
    na.rm = TRUE
  ) +
  
   scale_color_manual(values = c("#FFD700", "purple")) +
  
  theme_bw(base_size = 16) +

  xlab(paste0("PCoA1 (", round(Axis1.percent, 2), "%)")) +
  ylab(paste0("PCoA2 (", round(Axis2.percent, 2), "%)")) +
  
  labs(title = "Bray-Curtis | Feeding method",
       subtitle = yes) +
  
  theme(panel.grid = element_blank())
```

# PCOA | Probiotics


```{r, fig.width=9, fig.height=6}
yes <- paste0("R² = ", round(df_ok[row.names(df_ok) == "Probiotics" , "R2"], 4),
              " | F = ", round(df_ok[row.names(df_ok) == "Probiotics" , "F"], 4),
              " | p-value = ", round(df_ok[row.names(df_ok) == "Probiotics" , "Pr(>F)"], 4))


ggplot( princoor.pathotype.data, 
       aes(X,
           Y, 
           colour = Probiotics  )) + 
  geom_point(na.rm = TRUE) + 
  
  # As a stat, provide a geom
  stat_manual(
    geom = "segment", # function creates new xend/yend for segment
    fun = make_centroids,
    linewidth = 0.2,
    na.rm = TRUE
  ) +
  
   scale_color_manual(values = c("#FFD700", "purple")) +
  
  theme_bw(base_size = 16) +

  xlab(paste0("PCoA1 (", round(Axis1.percent, 2), "%)")) +
  ylab(paste0("PCoA2 (", round(Axis2.percent, 2), "%)")) +
  
  labs(title = "Bray-Curtis | Probiotics",
       subtitle = yes) +
  
  theme(panel.grid = element_blank())
```

# PCOA | Antibiotics


```{r, fig.width=9, fig.height=6}
yes <- paste0("R² = ", round(df_ok[row.names(df_ok) == "Antibiotics" , "R2"], 4),
              " | F = ", round(df_ok[row.names(df_ok) == "Antibiotics" , "F"], 4),
              " | p-value = ", round(df_ok[row.names(df_ok) == "Antibiotics" , "Pr(>F)"], 4))


ggplot( princoor.pathotype.data, 
       aes(X,
           Y, 
           colour = Antibiotics  )) + 
  geom_point(na.rm = TRUE) + 
  
  # As a stat, provide a geom
  stat_manual(
    geom = "segment", # function creates new xend/yend for segment
    fun = make_centroids,
    linewidth = 0.2,
    na.rm = TRUE
  ) +
  
   scale_color_manual(values = c("#FFD700", "purple")) +
  
  theme_bw(base_size = 16) +

  xlab(paste0("PCoA1 (", round(Axis1.percent, 2), "%)")) +
  ylab(paste0("PCoA2 (", round(Axis2.percent, 2), "%)")) +
  
  labs(title = "Bray-Curtis | Antibiotics",
       subtitle = yes) +
  
  theme(panel.grid = element_blank())
```


# PCOA | Ethnicity


```{r, fig.width=9, fig.height=6}
yes <- paste0("R² = ", round(df_ok[row.names(df_ok) == "Ethnicity" , "R2"], 4),
              " | F = ", round(df_ok[row.names(df_ok) == "Ethnicity" , "F"], 4),
              " | p-value = ", round(df_ok[row.names(df_ok) == "Ethnicity" , "Pr(>F)"], 4))


ggplot( princoor.pathotype.data, 
       aes(X,
           Y, 
           colour = Ethnicity  )) + 
  geom_point(na.rm = TRUE) + 
  
  # As a stat, provide a geom
  stat_manual(
    geom = "segment", # function creates new xend/yend for segment
    fun = make_centroids,
    linewidth = 0.2,
    na.rm = TRUE
  ) +
  
   scale_color_manual(values = c("#FFD700", "purple")) +
  
  theme_bw(base_size = 16) +

  xlab(paste0("PCoA1 (", round(Axis1.percent, 2), "%)")) +
  ylab(paste0("PCoA2 (", round(Axis2.percent, 2), "%)")) +
  
  labs(title = "Bray-Curtis | Ethnicity",
       subtitle = yes) +
  
  theme(panel.grid = element_blank())
```


```{r}

```











`https://cran.r-project.org/web/packages/hagis/vignettes/betadiversity.html`



