---
title: FIGURE_6B_VOLCANO_PATHWAY
author: Tram Bui
date: last-modified
format:
  html:
    toc: true
    toc-title: "TOC"
    toc-expand: 8
    toc-depth: 6
    toc-location: left
    code-fold: true
    code-summary: "Show the code"
    number-sections: false
    number-depth: 8
    page-layout: full
    embed-resources: true
    anchor-sections: true
    smooth-scroll: true
engine: knitr
knitr:
  opts_chunk:
    R.options:
      width: 120
editor_options: 
  chunk_output_type: console
---

```{r, echo=FALSE, results='hide'}
knitr::opts_chunk$set(message = FALSE,  
                      warning = FALSE)   
```

# Import

```{r}
df_pathway <- read.delim("baby_path.tsv")
names(df_pathway)[1] <- "Sample"
library(readxl)
df_clinic <- read_excel("df_clinic_final.xlsx")
df_clinic <- as.data.frame(df_clinic)
row.names(df_clinic) <- df_clinic$Sample
```

```{r}
df_pathway <- df_pathway[df_pathway$Sample %in% df_clinic$Sample, ]
```

```{r}
row.names(df_pathway) <- df_pathway$Sample

df_pathway <- df_pathway[row.names(df_clinic), ]

df_pathway -> df_pathway_ORI

df_pathway <- df_pathway[ , -c(1:3)]
```

# TERMNESS THEO `model == "prevalence"`

Sau khi có kết quả Massline, ta lọc theo Termness

```{r}
all_results <- read.delim("MAASLIN_PATHWAY_TERMNESS/all_results.tsv")
```

```{r}
# all_results_clean <- all_results |> subset(model == "abundance" & metadata == "Termness")

all_results_clean <- all_results |> subset(model == "prevalence" & metadata == "Termness")

all_results_clean <- all_results_clean[ , c(1,2,3,5,7,14,15,8,9)]

names(all_results_clean)[7:9] <- c("N.not.0", "pval", "qval")
```

```{r}
all_results_clean <- na.omit(all_results_clean)

all_results_clean$log10qval <- -log10(all_results_clean$qval)
```

```{r}
all_results_clean$LABEL <- ifelse(all_results_clean$log10qval > -log10(0.05) & (all_results_clean$coef < 1 | all_results_clean$coef > 1),
                                                             yes = TRUE,
                                                             no = FALSE)
```

```{r}
df_pathway -> abundance_clean

# quy ve percent
for(i in 1:nrow(abundance_clean)){
abundance_clean[i, ] <- 100*prop.table(abundance_clean[i, ])
}

t(abundance_clean) -> t_abundance_clean

mean_pathway <- apply(t_abundance_clean,
                      MARGIN = 1,
                      FUN = mean)

```

```{r}
mean_pathway_df <- data.frame(rel = mean_pathway,
                              feature= names(mean_pathway))
# trung binh cua cac ty le phan tram across baby

row.names(mean_pathway_df) <- NULL

df_merge_final <- merge(x = mean_pathway_df,
                       y = all_results_clean,
                       all.y = TRUE,
                       by = "feature")

df_merge_final <- na.omit(df_merge_final)

df_merge_final |> dplyr:::arrange(desc(LABEL)) -> df_merge_final
```

```{r}
library(dplyr)
df_merge_final <- df_merge_final |> dplyr:::mutate(LABEL_CHUAN = case_when(
  
  LABEL == TRUE & coef <= 0 ~ "TRUE_PRETERM",
  
  LABEL == TRUE & coef > 0 ~ "TRUE_TERM",
  
  LABEL == FALSE ~ "FALSE"
  
  
))

df_merge_final$LABEL_CHUAN <- factor(df_merge_final$LABEL_CHUAN,
                                     levels = c("FALSE", "TRUE_TERM", "TRUE_PRETERM"))
```


```{r, fig.width=9, fig.height=6}
library(ggplot2)
library(ggrepel)
library(grid)

ggplot(data = df_merge_final,
       mapping = aes(x = coef,
                     y = -log10(qval),
                     colour = LABEL_CHUAN,
                     size = rel)) +
  
  geom_point(alpha = 0.6,
             show.legend = T) +
  
  scale_size_continuous(range = c(1,10),
                        name = "Mean Rel. Abundance",
                        breaks = c(0.5, 0.1, 0.01 ),
                        labels = c("0.5%", "0.1%", "0.01%")
                        ) +
  
  scale_color_manual(values = c("gray", "coral", "purple"),
                     guide = "none"
                     ) +
  
  # scale_x_continuous(limits = c(-10,10)) +
  
  theme_classic(base_size = 16) +
  
  geom_hline(yintercept = -log10(0.05),
             color = "gray",
             lty = "dashed") +
  
  geom_vline(xintercept = 0,
             color = "gray",
             lty = "dashed") +

  
  labs(title = "Maaslin3 | ref_preterm | prevalence") +
  
  xlab("MaAsLin3 Coefficient") +
  
  ylab("-log10 q-value") +
  
  ggrepel::geom_text_repel(data = df_merge_final |> subset(LABEL == TRUE),
    mapping = aes(label = feature),
    # color = "blue",
    size = 4,
    show.legend = F)  +
  
  guides(size = guide_legend(override.aes = list(color = "gray")))

grid.text("term",
          x = unit(0.65, "npc"),
          y = unit(0.04, "npc"),
          gp = gpar(cex = 2,
                    col = "coral"))

grid.text("preterm",
          x = unit(0.15, "npc"),
          y = unit(0.04, "npc"),
          gp = gpar(cex = 2,
                    col = "purple"))
  
```

# TERMNESS THEO `model == "abundance"`

Sau khi có kết quả Massline, ta lọc theo Termness

```{r}
all_results <- read.delim("MAASLIN_PATHWAY_TERMNESS/all_results.tsv")
```

```{r}
all_results_clean <- all_results |> subset(model == "abundance" & metadata == "Termness")

# all_results_clean <- all_results |> subset(model == "prevalence" & metadata == "Termness")

all_results_clean <- all_results_clean[ , c(1,2,3,5,7,14,15,8,9)]

names(all_results_clean)[7:9] <- c("N.not.0", "pval", "qval")
```

```{r}
all_results_clean <- na.omit(all_results_clean)

all_results_clean$log10qval <- -log10(all_results_clean$qval)
```

```{r}
all_results_clean$LABEL <- ifelse(all_results_clean$log10qval > -log10(0.05) & (all_results_clean$coef < 1 | all_results_clean$coef > 1),
                                                             yes = TRUE,
                                                             no = FALSE)
```

```{r}
df_pathway -> abundance_clean

# quy ve percent
for(i in 1:nrow(abundance_clean)){
abundance_clean[i, ] <- 100*prop.table(abundance_clean[i, ])
}

t(abundance_clean) -> t_abundance_clean

mean_pathway <- apply(t_abundance_clean,
                      MARGIN = 1,
                      FUN = mean)

```

```{r}
mean_pathway_df <- data.frame(rel = mean_pathway,
                              feature= names(mean_pathway))
# trung binh cua cac ty le phan tram across baby

row.names(mean_pathway_df) <- NULL

df_merge_final <- merge(x = mean_pathway_df,
                       y = all_results_clean,
                       all.y = TRUE,
                       by = "feature")

df_merge_final <- na.omit(df_merge_final)

df_merge_final |> dplyr:::arrange(desc(LABEL)) -> df_merge_final
```

```{r}
library(dplyr)
df_merge_final <- df_merge_final |> dplyr:::mutate(LABEL_CHUAN = case_when(
  
  LABEL == TRUE & coef <= 0 ~ "TRUE_PRETERM",
  
  LABEL == TRUE & coef > 0 ~ "TRUE_TERM",
  
  LABEL == FALSE ~ "FALSE"
  
  
))

df_merge_final$LABEL_CHUAN <- factor(df_merge_final$LABEL_CHUAN,
                                     levels = c("FALSE", "TRUE_TERM", "TRUE_PRETERM"))
```


```{r, fig.width=9, fig.height=6}
library(ggplot2)
library(ggrepel)
library(grid)

ggplot(data = df_merge_final,
       mapping = aes(x = coef,
                     y = -log10(qval),
                     colour = LABEL_CHUAN,
                     size = rel)) +
  
  geom_point(alpha = 0.6,
             show.legend = T) +
  
scale_size_continuous(range = c(1,10),
                        name = "Mean Rel. Abundance",
                        breaks = c(0.5, 0.1, 0.01 ),
                        labels = c("0.5%", "0.1%", "0.01%")
                        ) +
  
  scale_color_manual(values = c("gray", "coral", "purple"),
                     breaks = c("FALSE", "TRUE_TERM", "TRUE_PRETERM"),
                     guide = "none"
                     ) +
  
  scale_x_continuous(limits = c(-10,10)) +
  
  theme_classic(base_size = 16) +
  
  geom_hline(yintercept = -log10(0.05),
             color = "gray",
             lty = "dashed") +
  
  geom_vline(xintercept = 0,
             color = "gray",
             lty = "dashed") +

  
  labs(title = "Maaslin3 | ref_preterm | abundance") +
  
  xlab("MaAsLin3 Coefficient") +
  
  ylab("-log10 q-value") +
  
  ggrepel::geom_text_repel(data = df_merge_final |> subset(LABEL == TRUE),
    mapping = aes(label = feature),
    # color = "blue",
    size = 4,
    show.legend = F)  +
  
  guides(size = guide_legend(override.aes = list(color = "gray")))

grid.text("term",
          x = unit(0.65, "npc"),
          y = unit(0.04, "npc"),
          gp = gpar(cex = 2,
                    col = "coral"))

grid.text("preterm",
          x = unit(0.15, "npc"),
          y = unit(0.04, "npc"),
          gp = gpar(cex = 2,
                    col = "purple"))
  
```


# TEST

```{r}
df_merge_test <- merge(x = df_pathway_ORI,
                       y = df_clinic[ , c("Sample", "Termness")],
                       all.x = T,
                       by = "Sample")

aggregate(FASYN.INITIAL.PWY..superpathway.of.fatty.acid.biosynthesis.initiation..E..coli. ~ Termness,
          data = df_merge_test,
          FUN = mean)
```





