---
title: "MASSLIN"
output: html_document
editor_options: 
  chunk_output_type: console
---

https://biovcnet.github.io/_pages/NetworkScience_SparCC.nb.html

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004226


# SPECIES

```{r}
df_species <- read.delim("baby_species.tsv")
names(df_species)[1] <- "Sample"
library(readxl)
df_clinic <- read_excel("df_clinic_final.xlsx")
df_clinic <- as.data.frame(df_clinic)
row.names(df_clinic) <- df_clinic$Sample
```

```{r}
df_species <- df_species[df_species$Sample %in% df_clinic$Sample, ]
```

```{r}
row.names(df_species) <- df_species$Sample

df_species <- df_species[row.names(df_clinic), ]

df_species -> df_species_ORI

df_species <- df_species[ , -1]
```

```{r}
library(readxl)
df_SCFA <- read_excel("SCFA_stool.xlsx")
df_SCFA <- as.data.frame(df_SCFA)

names(df_SCFA) <- c("Sample", "acetate", "propionate", "isobutyrate", "butyrate")

df_SCFA$acetate <- log(df_SCFA$acetate+0.001)
df_SCFA$propionate <- log(df_SCFA$propionate+0.001)
df_SCFA$isobutyrate <- log(df_SCFA$isobutyrate+0.001)
df_SCFA$butyrate <- log(df_SCFA$butyrate+0.001)

row.names(df_SCFA) <- df_SCFA$Sample

df_SCFA <- df_SCFA[row.names(df_clinic), ]

# df_SCFA <- df_SCFA[ , -1]
```

```{r}
identical(df_clinic$Sample, df_SCFA$Sample)

df_clinic <- merge(x = df_clinic,
                  y = df_SCFA,
                  all.x = T,
                  by = "Sample")

row.names(df_clinic) <- df_clinic$Sample
```

# MAASLIN3 | SPECIES | ALL VARIABLES

```{r}
library(maaslin3)

df_clinic$Termness <- factor(df_clinic$Termness,
                             levels = c("preterm", "term"))

df_clinic$Sex <- factor(df_clinic$Sex,
                             levels = c("Male", "Female"))

df_clinic$Delivery_mode <- factor(df_clinic$Delivery_mode,
                             levels = c("Vaginal", "C-section"))

df_clinic$Feeding_method <- factor(df_clinic$Feeding_method,
                             levels = c("Non-breastfed", "Breastfed"))

df_clinic$Antibiotics <- factor(df_clinic$Antibiotics,
                             levels = c("No", "Yes"))

df_clinic$Probiotics <- factor(df_clinic$Probiotics,
                             levels = c("No", "Yes"))

df_clinic$Ethnicity <- factor(df_clinic$Ethnicity,
                             levels = c("non-European", "European"))



###############################

fit_out <- maaslin3(input_data = df_species,
                    input_metadata = df_clinic,
                    output = 'MAASLIN_SPECIES_TERMNESS',
                    formula = '~ Termness +  Read_depth',
                    normalization = 'TSS',
                    transform = 'LOG',
                    augment = TRUE,
                    # standardize = TRUE,
                     min_abundance = 0.0001,
                    min_prevalence = 0.1,
                    max_significance = 0.1,
                    median_comparison_abundance = TRUE,
                    median_comparison_prevalence = FALSE,
                    max_pngs = 100,
                    cores = 1,
                    save_models = TRUE)

################################



fit_out <- maaslin3(input_data = df_species,
                    input_metadata = df_clinic,
                    output = 'ALL_VAR_SPECIES_MAASLIN_SCFA',
                    formula = '~ Termness + Sex + Delivery_mode + Feeding_method + Antibiotics + Probiotics + Ethnicity + Read_depth + acetate + propionate + isobutyrate + butyrate',
                    #formula = '~ Termness +  Read_depth',
                    normalization = 'TSS',
                    transform = 'LOG',
                    augment = TRUE,
                    # standardize = TRUE,
                     min_abundance = 0.0001,
                    min_prevalence = 0.1,
                    max_significance = 0.1,
                    median_comparison_abundance = TRUE,
                    median_comparison_prevalence = FALSE,
                    max_pngs = 100,
                    cores = 1,
                    save_models = TRUE)
```


```{r}
df_SCFA <- df_SCFA[ , -1]
df_clinic <- df_clinic[ , -1]
```


```{r}
all_results_species <- read.delim("ALL_VAR_SPECIES_MAASLIN_SCFA/all_results.tsv")
length(unique(all_results_species$feature))

all_results_species <- all_results_species |> subset(model == "prevalence") |> dplyr:::arrange(qval_individual)

```

```{r}
df_clean_species <- all_results_species[complete.cases(all_results_species$coef), ]
length(unique(df_clean_species$feature))

write.csv(df_clean_species, "df_clean_species.csv", row.names = F)
```

```{r}
species_norm <- read.delim("ALL_VAR_SPECIES_MAASLIN_SCFA/features/data_norm.tsv")
```

```{r}
df_species_ready <- species_norm[   , names(species_norm) %in% df_clean_species$feature]
row.names(df_species_ready) <- species_norm$feature
```

# PATHWAY

Functional profiles were renormalized to CPM using the ‘humann2_renorm_table’ function.

Predicted stool metabolite profiles were generated from the gene profiles using MelonnPan using default parameters

```{r}
df_pathway <- read.delim("baby_path.tsv")
names(df_pathway)[1] <- "Sample"
row.names(df_pathway) <- df_pathway$Sample
```

```{r}
df_pathway <- df_pathway[df_pathway$Sample %in% row.names(df_clinic), ]
```

```{r}
df_pathway <- df_pathway[row.names(df_clinic), ]

df_pathway <- df_pathway[ , -c(1:3)]
```

```{r}
library(maaslin3)

###############################

fit_out <- maaslin3(input_data = df_pathway,
                    input_metadata = df_clinic,
                    output = 'MAASLIN_PATHWAY_TERMNESS',
                    formula = '~ Termness +  Read_depth',
                    normalization = 'NONE',
                    transform = 'LOG',
                    augment = TRUE,
                    # standardize = TRUE,
                     min_abundance = 0.0001,
                    min_prevalence = 0.1,
                    max_significance = 0.1,
                    median_comparison_abundance = TRUE,
                    median_comparison_prevalence = FALSE,
                    max_pngs = 100,
                    cores = 1,
                    save_models = TRUE)

################################


fit_out <- maaslin3(input_data = df_pathway,
                    input_metadata = df_clinic,
                    output = 'ALL_VAR_PATHWAY_MAASLIN_SCFA',
                    formula = '~ Termness + Sex + Delivery_mode + Feeding_method + Antibiotics + Probiotics + Ethnicity + Read_depth + acetate + propionate + isobutyrate + butyrate',
                    #formula = '~ Termness +  Read_depth',
                    normalization = 'NONE',
                    transform = 'LOG',
                    augment = TRUE,
                    # standardize = TRUE,
                     min_abundance = 0.0001,
                    min_prevalence = 0.1,
                    max_significance = 0.1,
                    median_comparison_abundance = TRUE,
                    median_comparison_prevalence = FALSE,
                    max_pngs = 100,
                    cores = 1,
                    save_models = TRUE)
```

```{r}
all_results_pathway <- read.delim("ALL_VAR_PATHWAY_MAASLIN_SCFA/all_results.tsv")
length(unique(all_results_pathway$feature))

all_results_pathway <- all_results_pathway |> subset(model == "prevalence") |> dplyr:::arrange(qval_individual)
# all_results_pathwayabundance <- all_results_pathway |> subset(model == "abundance") |> dplyr:::arrange(qval_individual)
length(unique(all_results_pathway$feature))
```


```{r}
df_clean_pathway <- all_results_pathway[complete.cases(all_results_pathway$coef), ]

write.csv(df_clean_pathway, "df_clean_pathway.csv", row.names = F)
```

```{r}
pathway_norm <- read.delim("ALL_VAR_PATHWAY_MAASLIN_SCFA/features/data_norm.tsv")
```

```{r}
df_pathway_ready <- pathway_norm[, names(pathway_norm) %in% df_clean_pathway$feature]

row.names(df_pathway_ready) <- pathway_norm$feature
```

# SCFA

```{r}
library(maaslin3)
library(readxl)
df_SCFA <- read_excel("SCFA_stool.xlsx")
df_SCFA <- as.data.frame(df_SCFA)

names(df_SCFA) <- c("Sample", "acetate", "propionate", "isobutyrate", "butyrate")

# df_SCFA$acetate <- log(df_SCFA$acetate+0.001)
# df_SCFA$propionate <- log(df_SCFA$propionate+0.001)
# df_SCFA$isobutyrate <- log(df_SCFA$isobutyrate+0.001)
# df_SCFA$butyrate <- log(df_SCFA$butyrate+0.001)

row.names(df_SCFA) <- df_SCFA$Sample

df_SCFA <- df_SCFA[row.names(df_clinic), ]
df_SCFA <- df_SCFA[,-1]
fit_out <- maaslin3(input_data = df_SCFA,
                    input_metadata = df_clinic,
                    output = 'ALL_VAR_MAASLIN_SCFA',
                    formula = '~ Termness + Sex + Delivery_mode + Feeding_method + Antibiotics + Probiotics + Ethnicity + Read_depth',
                    #formula = '~ Termness +  Read_depth',
                    normalization = 'NONE',
                    transform = 'LOG',
                    augment = TRUE,
                    # standardize = TRUE,
                     min_abundance = 0.0001,
                    min_prevalence = 0.1,
                    max_significance = 0.1,
                    median_comparison_abundance = FALSE,
                    median_comparison_prevalence = FALSE,
                    max_pngs = 100,
                    cores = 1,
                    save_models = TRUE)
```

```{r}
all_results_scfa <- read.delim("ALL_VAR_MAASLIN_SCFA/all_results.tsv")

all_results_scfa <- all_results_scfa |> subset(model == "abundance")

df_clean_SCFA <- all_results_scfa[ complete.cases(all_results_scfa$coef), ]

write.csv(df_clean_SCFA, "df_clean_SCFA.csv", row.names = F)
```

```{r}
scfa_norm <- read.delim("ALL_VAR_MAASLIN_SCFA/features/data_norm.tsv")
```

```{r}
df_SCFA_ready <- scfa_norm

row.names(df_SCFA_ready) <- scfa_norm$feature

df_SCFA_ready <- df_SCFA_ready[ , -1]
```


# COMBINE ALL

```{r}
identical(row.names(df_SCFA_ready), row.names(df_species_ready))
identical(row.names(df_pathway_ready), row.names(df_species_ready))
df_all <- cbind(df_SCFA_ready,
                df_species_ready[ , ],
                df_pathway_ready[ , ])

write.csv(df_SCFA_ready, "df_SCFA_ready.csv", row.names = F)
write.csv(df_species_ready, "df_species_ready.csv", row.names = F)
write.csv(df_pathway_ready, "df_pathway_ready.csv", row.names = F)

```

```{r}
sapply(X = df_all, 
        FUN = function(x){  length(which(is.na(x)))  }   ) -> ok_na

write.csv(df_all, "df_all_raw.csv", row.names = F)
```

# COR P-VALUE

```{r}
library(rstatix)

library(foreach)
library(doParallel)

# How many cores does your CPU have
# n_cores <- detectCores()
# n_cores
# cluster <- makeCluster(n_cores - 2)
# registerDoParallel(cluster)

library(Hmisc)

res <- Hmisc:::rcorr(as.matrix(df_all), type = "spearman")
p_all   <- res$P

p_all <- as.matrix(p_all)
```

```{r}
p_all[which(upper.tri(p_all, diag = T))] <- NA
```


```{r}
p_all <- as.data.frame(p_all)

row.names(p_all) -> p_all$var1

row.names(p_all) <- NULL

p_all <- p_all[ , c(ncol(p_all), 1: (ncol(p_all)  - 1)
                    )
                ]

```

```{r}
library(tidyr)
df_long_p <- tidyr:::pivot_longer(p_all,
                                cols = c(2:ncol(p_all)),
                                names_to = "var2",
                                values_to = "p_value") |> as.data.frame()

df_long_p <- na.omit(df_long_p)

```

# COR MATRIX


```{r}
library(rstatix)

library(foreach)
library(doParallel)

# How many cores does your CPU have
# n_cores <- detectCores()
# n_cores
# cluster <- makeCluster(n_cores - 2)
# registerDoParallel(cluster)

library(Hmisc)

res <- Hmisc:::rcorr(as.matrix(df_all), type = "spearman")
r_all   <- res$r

r_all <- as.matrix(r_all)
```

```{r}
r_all[which(upper.tri(r_all, diag = T))] <- NA
```


```{r}
r_all <- as.data.frame(r_all)

row.names(r_all) -> r_all$var1

row.names(r_all) <- NULL

r_all <- r_all[ , c(ncol(r_all), 1: (ncol(r_all)  - 1)
                    )
                ]

```

```{r}
library(tidyr)
df_long_r <- tidyr:::pivot_longer(r_all,
                                cols = c(2:ncol(r_all)),
                                names_to = "var2",
                                values_to = "cor") |> as.data.frame()

df_long_r <- na.omit(df_long_r)

```

# COMBINE COR AND P

```{r}
df_long_p$id <- paste0(df_long_p$var1, df_long_p$var2)

df_long_r$id <- paste0(df_long_r$var1, df_long_r$var2)

setdiff(df_long_p$id, df_long_r$id)
setdiff(df_long_r$id, df_long_p$id)

identical(df_long_p$id, df_long_r$id)
```


```{r}
df_long_master <- cbind(df_long_r[ , -4],
                        df_long_p[ , 3, drop = F])

df_long_master <- df_long_master |> subset(cor > -0.99 & cor < 0.99 & p_value < 0.9)

df_long_master |> dplyr:::arrange(p_value) -> df_long_master

df_long_master$FDR <- p.adjust(df_long_master$p_value, method = "BH")

df_long_master_final <- df_long_master[ df_long_master$FDR < 0.1 , ]

write.csv(df_long_master_final, "data_cor_spearman_80baby.csv", row.names = F)
```


```{r}

```

















